{% set name = "avidaq" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/avidaq-{{ version }}.tar.gz
  sha256: e1691bce07c54b890cec8a7feadb19fd47fef1fb6d689b9b2ff32502a49df6ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari
    - numpy
    - pycromanager
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - avidaq
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/avidaq/
  summary: controls for napari and micromanger
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
